packages:
  - packages/*
  - examples/*
  - tests/e2e

catalog:
  '@livestore/adapter-web': 0.4.0-dev.22
  '@livestore/adapter-node': 0.4.0-dev.22
  '@livestore/devtools-vite': 0.4.0-dev.22
  '@livestore/livestore': 0.4.0-dev.22
  '@livestore/peer-deps': 0.4.0-dev.22
  '@livestore/react': 0.4.0-dev.22
  '@livestore/sync-cf': 0.4.0-dev.22
  '@livestore/utils': 0.4.0-dev.22
  '@livestore/wa-sqlite': 0.4.0-dev.22
  '@effect/platform': 0.93.8
  '@effect/platform-node': 0.103.0
  effect: 3.19.12
